name: WigglerSim
description: An absolute bare-bones web app.
version: 2.2.0

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  DollLibCorrect:
    git:
      url: git://github.com/FarragoFiction/DollLibCorrect.git
      ref: Dart-2.2.0

  BlackJack:
    git:  git://github.com/FarragoFiction/BlackJack.git
  CommonLib:
    git:
      url: git://github.com/FarragoFiction/CommonLib.git
      ref: Dart-2.2.0
  TextEngine:
    git:
      url: git://github.com/FarragoFiction/TextEngine.git
      ref: Dart-2.2.0
  RenderingLib:
    git:
      url: git://github.com/FarragoFiction/RenderingLib.git
      ref: Dart-2.2.0
  ImageLib:
    git:
      url: git://github.com/FarragoFiction/ImageLib.git
      ref: Dart-2.2.0

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0

web:
  compiler:
    debug: dartdevc
