name: WigglerSim
description: An absolute bare-bones web app.
version: 2.2.0

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  DollLibCorrect:
    git: git://github.com/FarragoFiction/DollLibCorrect.git
  BlackJack:
    git:  git://github.com/FarragoFiction/BlackJack.git
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  TextEngine:
    git: git://github.com/FarragoFiction/TextEngine.git
  RenderingLib:
    git: git://github.com/FarragoFiction/RenderingLib.git

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0

web:
  compiler:
    debug: dartdevc
